version: "3.6"
services:
  poc:
    container_name: poc
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - 3000:3000
        - 49153:49153
    volumes:
        - .:/app
        - /app/node_modules
    networks:
        - poc_network
    restart: always
    command: npm run dev

networks:
  poc_network:
      name: poc_network
      driver: bridge